[project]
name = "olist-ecommerce"
version = "0.1.0"
description = "Data engineering portfolio project"
readme = "README.md"
authors = [
    { name = "Felix Manuel Aguila Alonso", email = "feloaguila@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dlt[duckdb,sql-database]>=1.30.0",
    "pg8000>=1.31.5",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
seed = "olist.oltp.seed:main"
simulate = "olist.oltp.simulator:main"
ingest = "olist.pipeline.ingestion.dlt_ingestion:main"

[dependency-groups]
dbt-duckdb = [
    "dbt-duckdb>=1.11.0",
]
dev = [
    "ipykernel>=7.3.0",
]
orchestration = [
    "prefect>=3.1.16",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/olist"]

