services:
  ecommerce_db:
    container_name: ecommerce_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ecommerce_db:/var/lib/postgresql/data

volumes:
  ecommerce_db: